name: Update Formula
on:
  repository_dispatch:
    types: [update-sample-tauri-app]

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          echo "Hello, ${{ github.event.client_payload.version }}"
          echo "Hello, ${{ github.event.client_payload.sha }}"
          echo "URL: ${{ github.event.client_payload.upload_url }}"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update formula file
        run: |
          VERSION=${{ github.event.client_payload.version }}
          URL="https://github.com/sei-12/sample-tauri-app/releases/download/app-v$VERSION/sample-tauri-app_"$VERSION"_aarch64.dmg"
          data=$(cat <<EOF > Casks/sample-tauri-app.rb
              cask "sample-tauri-app" do 
                version "$VERSION"
                sha256 "${{ github.event.client_payload.sha }}"
                url "$URL"
                name "sample-tauri-app"
                desc "A sample application"
                homepage "https://github.com/sei-12/sample-tauri-app"

                app "sample-tauri-app.app"

                zap trash: [
                  "~/Library/Application Support/com.sample-tauri-app.app",
                ]
              end
          EOF
          )
      - name: Commit version change
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "sei-12"
          git add -A
          git commit -m "Update version to ${{ github.event.client_payload.version }} for sample-tauri-app"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}